In [7]:
# performance comparison
import numpy as np

In [9]:
import time
size=10000000
# python list
python_list=list(range(size))
start=time.time()
list_squared=[x**2 for x in python_list]
end=time.time()
print("python list time:",end-start,"seconds")

# Numpy arrays
np_array=np.array(python_list)
start=time.time()
array_squared=np_array**2
end=time.time()
print("Numpy array time:",end-start,"second")

python list time: 1.5383951663970947 seconds
Numpy array time: 0.044663190841674805 second


In [11]:
# Memory usage Comparison
import sys
print("python list size:",sys.getsizeof(python_list)*len(python_list))
print("Numpy array size:",np_array.nbytes)

python list size: 800000560000000
Numpy array size: 80000000


In [16]:
# creating numpy array from list
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(type(arr))
print(arr.shape)

arr2=np.array([1,2,3,4,5,"prime",3.14])
print(arr2,type(arr2),arr2.shape)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(9,)
['1' '2' '3' '4' '5' 'prime' '3.14'] <class 'numpy.ndarray'> (7,)


In [20]:
# 2D array-matrix
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)
print(type(arr3))
print(arr3.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)


In [29]:
#  create using build-in methods
arr1=np.zeros((3,4),dtype="int64")  #prefill
print(arr1)
print(arr1.shape)

arr2=np.ones((4,5))
print(arr2)
print(arr2.shape)

arr3=np.full((4,5),100)  #prefill with val
print(arr3,arr3.shape)

arr4=np.eye(4)  #identity matrix
print(arr4,arr4.shape)

arr5=np.arange(0,11,2)  #range elements
print(arr5,arr5.shape)

arr6=np.linspace(1,100,4)  #evenly spaced arrays
print(arr6,arr6.shape)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
(3, 4)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(4, 5)
[[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]] (4, 5)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4)
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)


In [30]:
# Reshaping array 
arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)
reshaped=arr.reshape((3,2))
print(reshaped,reshaped.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
